# Generated by Django 3.2.8 on 2021-11-11 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametr', models.CharField(max_length=255, verbose_name='Диаметр')),
            ],
            options={
                'verbose_name': 'Диаметр',
                'verbose_name_plural': 'Диаметрлер',
            },
        ),
        migrations.CreateModel(
            name='Localities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Елді мекен атауы')),
            ],
            options={
                'verbose_name': 'Елді мекен',
                'verbose_name_plural': 'Елді мекендер',
            },
        ),
        migrations.CreateModel(
            name='RuralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ауылдық округ атауы')),
            ],
            options={
                'verbose_name': 'Ауылдық округ',
                'verbose_name_plural': 'Ауылдық округтар',
            },
        ),
        migrations.CreateModel(
            name='LocalitiesWater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetCount', models.IntegerField(verbose_name='Көше саны')),
                ('populationCount', models.IntegerField(verbose_name='Халық саны')),
                ('subscribersCount', models.IntegerField(verbose_name='Абонент саны ')),
                ('springSource', models.CharField(max_length=255, verbose_name='Бұлақ көзі')),
                ('waterDebit', models.CharField(max_length=255, verbose_name='Судың дебеті')),
                ('waterReserves', models.CharField(max_length=255, verbose_name='Жер асты су қоры хаттамасы')),
                ('waterLength', models.CharField(max_length=255, verbose_name='Су құбырының ұзындығы (км)')),
                ('yearConstruction', models.IntegerField(verbose_name='Салынған жылы')),
                ('waterStructure', models.CharField(max_length=255, verbose_name='Су құбырының құрылымы')),
                ('newPipes', models.CharField(max_length=255, verbose_name='Жаңартылған құбырлар (км)')),
                ('newYearConstruction', models.IntegerField(verbose_name='Жаңартылған жылы')),
                ('needToUpdate', models.CharField(max_length=255, verbose_name='Жаңартуды қажет ететіні (км) ')),
                ('wateMetersCount', models.IntegerField(verbose_name='Су есептегіш құралдары  (саны)')),
                ('diametress', models.ManyToManyField(related_name='localitiesWater', to='city.Diametr', verbose_name='Диаметры')),
                ('localities', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localitiesWater', to='city.localities', verbose_name='Елді мекен')),
            ],
            options={
                'verbose_name': 'Су бойынша',
                'verbose_name_plural': 'Су бойынша',
            },
        ),
        migrations.AddField(
            model_name='localities',
            name='rural',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='city.ruraldistrict', verbose_name='Ауылдық округ'),
        ),
    ]
