# Generated by Django 3.2.8 on 2021-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localities',
            name='image',
            field=models.ImageField(default=1, upload_to='Localities/', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ruraldistrict',
            name='image',
            field=models.ImageField(default=1, upload_to='Rurals/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
