# Generated by Django 3.2.8 on 2021-11-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_auto_20211112_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localitiesgas',
            options={'verbose_name': 'Газ бойынша', 'verbose_name_plural': 'Газ бойынша'},
        ),
        migrations.AlterModelOptions(
            name='localitieswater',
            options={'verbose_name': 'Су бойынша', 'verbose_name_plural': 'Су бойынша'},
        ),
        migrations.AddField(
            model_name='localitieselectr',
            name='trCip',
            field=models.IntegerField(default=985, verbose_name='СИП кабель ВЛ-06 кВт (метр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localitieselectr',
            name='trNumber',
            field=models.IntegerField(default=2, verbose_name='Трансформатор (КТПН)  саны '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localitieselectr',
            name='trVl',
            field=models.IntegerField(default=4889, verbose_name='ВЛ-04 кВт (метр)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localitieselectr',
            name='trbaganaNumber',
            field=models.IntegerField(default=80, verbose_name='Трансформатордағы бағаналардың жалпы саны (дана)'),
            preserve_default=False,
        ),
    ]
