# Generated by Django 3.2.8 on 2021-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210908_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyline',
            name='diametr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='polyline',
            name='sh_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
