# Generated by Django 3.2.8 on 2021-11-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20211112_1246'),
        ('main', '0007_auto_20211008_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='polyline',
            name='localities',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='polylines', to='city.localities', verbose_name='Елді мекендер'),
        ),
    ]
