# Generated by Django 3.2.8 on 2021-11-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_polyline_localities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polyline',
            name='description',
        ),
        migrations.RemoveField(
            model_name='polyline',
            name='diametr',
        ),
        migrations.RemoveField(
            model_name='polyline',
            name='sh_count',
        ),
        migrations.CreateModel(
            name='PolyLineRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=255, verbose_name='Ені')),
                ('hectar', models.CharField(max_length=255, verbose_name='Гектар')),
                ('beton', models.CharField(max_length=255, verbose_name='Асфальт')),
                ('goodSituation', models.CharField(max_length=255, verbose_name='жақсы шқ.')),
                ('badSituation', models.CharField(max_length=255, verbose_name='қанағатсыз, шқ.')),
                ('yearConstruction', models.CharField(max_length=255, verbose_name='Салынған жылы ')),
                ('polyline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='road', to='main.polyline', verbose_name='Полилиния')),
            ],
        ),
    ]
