# Generated by Django 3.2.8 on 2021-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211112_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polylineroad',
            name='badSituation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='қанағатсыз, шқ.'),
        ),
    ]
