# Generated by Django 3.2.8 on 2021-11-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_auto_20211119_1937'),
        ('main', '0010_alter_polylineroad_badsituation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Мәселе')),
                ('solution', models.CharField(max_length=255, verbose_name='Шешімі')),
                ('localty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.localities', verbose_name='Елді мекен атауы')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.polylinetypes', verbose_name='Тип')),
            ],
        ),
    ]
