# Generated by Django 3.2.8 on 2021-11-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_relevant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polyline',
            options={'verbose_name': 'Полилиния', 'verbose_name_plural': 'Полилиниялар'},
        ),
        migrations.AlterModelOptions(
            name='polylineroad',
            options={'verbose_name': 'Полилиния жол', 'verbose_name_plural': 'Полилиния жолдар'},
        ),
        migrations.AlterModelOptions(
            name='polylinetypes',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типтер'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позициялар'},
        ),
        migrations.AlterModelOptions(
            name='relevant',
            options={'verbose_name': 'Өзекті мәселе', 'verbose_name_plural': 'Өзекті мәселелер'},
        ),
        migrations.AlterField(
            model_name='relevant',
            name='question',
            field=models.TextField(max_length=255, verbose_name='Мәселе'),
        ),
        migrations.AlterField(
            model_name='relevant',
            name='solution',
            field=models.TextField(max_length=255, verbose_name='Шешімі'),
        ),
    ]
