# Generated by Django 3.2.8 on 2021-11-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0005_auto_20211119_1937'),
        ('main', '0012_auto_20211126_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevant',
            name='localty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localty', to='city.localities', verbose_name='Елді мекен атауы'),
        ),
        migrations.AlterField(
            model_name='relevant',
            name='question',
            field=models.TextField(verbose_name='Мәселе'),
        ),
        migrations.AlterField(
            model_name='relevant',
            name='solution',
            field=models.TextField(verbose_name='Шешімі'),
        ),
        migrations.AlterField(
            model_name='relevant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='main.polylinetypes', verbose_name='Тип'),
        ),
    ]
