# Generated by Django 3.2.8 on 2021-11-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211126_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevant',
            name='waiting_result',
            field=models.TextField(default=1, verbose_name='Күтілетін нәтиже'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relevant',
            name='question',
            field=models.TextField(verbose_name='Өзекті мәселенің атауы '),
        ),
        migrations.AlterField(
            model_name='relevant',
            name='solution',
            field=models.TextField(verbose_name='Шешу жолдары'),
        ),
    ]
